AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Tables for Jeffws Service Integration Tests

Outputs:
  StackRegion:
    Value: !Ref AWS::Region
  DocumentTableName:
    Value: !Ref DocumentTable

Resources:
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ID
        Type: Number
